### ISSUE TITLE
local debug报错   [: localx: unexpected operator

### ISSUE THREAD

**Issue by nestattacked** [alibaba/serverless-vscode#112]
好像是templates/fun.sh脚本中的if语句等号不对？应该用一个=，bash才是两个==？

**Comment by ChanDaoH** [comment]
vscode 插件的版本是多少？麻烦贴一下命令行的交互呢？

**Comment by nestattacked** [comment]
插件版本1.9.0、vscode版本1.38.1、系统ubuntu18.04
命令是使用插件debug ~/.aliyun-serverless/bin/fun.sh local start service/function -d 3000
命令是可以运行的，就是会提示两句错误

**Comment by ChanDaoH** [comment]
sh 里面用两个等号是没问题的，可以截图下交互图吗？

**Comment by nestattacked** [comment]
![debug](https://user-images.githubusercontent.com/4384269/64950378-ce15fc80-d8ad-11e9-8f84-6cce7fe07900.png)
我好像讲错了，我用的bash

**Comment by yuantongkang** [comment]
我也遇到了和这个一样的问题

**Comment by ChanDaoH** [comment]
用的系统也是 ubuntu 吗？

**Comment by yuantongkang** [comment]
> 用的系统也是 ubuntu 吗？

用的是wsl2的ubuntu
