### ISSUE TITLE
本地资源树支持更多的编辑

### ISSUE THREAD

**Issue by vangie** [alibaba/serverless-vscode#117]
1. 支持将某个函数拷贝到另外一个服务下，包括跨 template.yml 文件操作
2. 支持将某个函数剪切到另外一个服务下
3. 支持服务的拷贝和剪切
4. 支持 redo/undo
5. 考虑支持函数和服务的改名。

**Comment by ChanDaoH** [comment]
以支持将 某个函数的描述拷贝到另外一个服务下

**Comment by ChanDaoH** [comment]
其他相关支持是否有具体场景呢？可以新开个 issue 讨论
