### ISSUE TITLE
增强调试面板

### ISSUE THREAD

**Issue by vangie** [alibaba/serverless-vscode#118]
1. 调试面板支持配置 quick run/debug 的默认事件文件。
2. 事件文件归结到非提交目录
3. 远端调用复用调试面板
4. 资源树考虑去掉快速调试和快速运行，改成打开调试面板
5.  FC:local Run 更名为 Local: Quick Run ， debug 类似。
6. FC: invoke Panel 更名为 Run/Debug Panel

**Comment by ChanDaoH** [comment]
Done
