### ISSUE TITLE
debug fc with http trigger cannot specify paramters in auto launch url

### ISSUE THREAD

**Issue by nonew** [alibaba/serverless-vscode#128]
**Is your feature request related to a problem? Please describe.**
when you debug an FC with an HTTP trigger, it will launch the browser with default URL which does not have any parameters, developer have to specify parameter manually. it is very inconvenient.

**Describe the solution you'd like**
should be able to specify parameters in IDE, such as VSCode

**Describe alternatives you've considered**

**Additional context**

**Comment by ChanDaoH** [comment]
您的 vscode 插件版本是多少？目前 1.12.3 版本的插件，Local Debug HTTP Trigger 后，会自动启动 VSCode 调试模式并且在终端 Terminal 中输出 HTTP Trigger 访问的 Url 链接。您可以在浏览器或者 Postman 中访问该 Url 并配置参数
