### ISSUE TITLE
如何创建event？

### ISSUE THREAD

**Issue by feibenren** [alibaba/serverless-vscode#131]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChanDaoH** [comment]
您指的如何创建 Event，是指的要为普通 Event Trigger 函数配置本地运行或调试时的 Event 事件信息吗？

**Comment by ChanDaoH** [comment]
v1.16.0 版本中，Event 信息可以在 Invoke Panel 中创建。
![image](https://user-images.githubusercontent.com/19430792/69115083-4f625900-0ac2-11ea-8132-d5c2c97dba8d.png)
![image](https://user-images.githubusercontent.com/19430792/69115090-56896700-0ac2-11ea-8b66-477a7e745cea.png)
