### ISSUE TITLE
插件无法正常使用

### ISSUE THREAD

**Issue by yalishizhude** [alibaba/serverless-vscode#139]
**Describe the bug**
插件列表一直为空，代码无法调试。

**To Reproduce**
1. 点击 Bind New Account 之后REMOTE RESOURCES 未显示添加项
2. 点击 Create Function 之后 LOCAL RESOURCES 未显示添加项

**Expected behavior**
应该正常显示添加项
添加的函数可以点击进行调试和上传

**Screenshots**
![image](https://user-images.githubusercontent.com/3870098/67300520-a1927780-f520-11e9-9482-cdf1aae65b9e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - VSCode Version:  1.40.0-insider
 - Aliyun Serverless Extension Version 1.12.3

**Comment by yalishizhude** [comment]
![image](https://user-images.githubusercontent.com/3870098/67301007-6ba1c300-f521-11e9-99bd-2f4c64129624.png)

**Comment by ChanDaoH** [comment]
您这边右侧的插件还在初始化，初始化完成后在函数入口文件就会有 Local Run 和 Local Debug 字样。
您反馈的正常添加项是指的什么？

**Comment by yalishizhude** [comment]
![](http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/assets/pic/126086/cn_zh/1563461335893/deploy-result.png)

上图是官方文档的截图，正常情况下左边应该是有对应的账号列表和文件列表的，但是却是空的，导致我无法调试和上传。
关于加载的问题我已经等了10分钟了，难道还没初始化完成？而且感觉很耗CPU

**Comment by ChanDaoH** [comment]
您这边是不是在安装的时候关闭了 vscode？您这边 vscode 版本是多少？在插件市场重新安装下呢

**Comment by ChanDaoH** [comment]
目前最新的 v1.16.0 版本优化了资源树加载的速度，是否还有上述问题呢？
