### ISSUE TITLE
如何方便更新远程代码到本地以及查看代码变更？

### ISSUE THREAD

**Issue by phpsxg** [alibaba/serverless-vscode#180]
1.如何更新远程代码到本地？类似于git pull命令
因为每次更新到本地都需要先 把template.yml 中服务的块删除，然后再导入这样很麻烦

2.如何查看本地代码修改了哪些？类似于git status git diff命令
有时候我想知道我是否修改了本地的代码

**Comment by vangie** [comment]
> 因为每次更新到本地都需要先 把template.yml 中服务的块删除

为什么需要删除？

**Comment by ChanDaoH** [comment]
新版本中允许选择导入的目录地址
diff 功能会新开 issue 跟进
