### ISSUE TITLE
Region is not available because you have configured custom endpoint!

### ISSUE THREAD

**Issue by LuckyStarry** [alibaba/serverless-vscode#249]
尝试切换Region时提示“Region is not available because you have configured custom endpoint!”，但是并没有找到在哪里设置Region。

**Comment by briefguo** [comment]
嗯，我也遇到了.
能走Web进行设置吗？

**Comment by llyo** [comment]
目前只能手动修改配置：~/.fcli/config.yaml  这个配置文件中加上
`enableCustomEndpoint: true`

**Comment by briefguo** [comment]
👌 嗯，可以的，我先这样解决了.

是不是考虑可以变成一个 UI界面内 支持的功能

**Comment by LuckyStarry** [comment]
暂时靠 @llyo 大佬提供的方案解决了，感谢！
