### ISSUE TITLE
invalid signature: 0x6d783f3c

### ISSUE THREAD

**Issue by sikros** [alibaba/serverless-vscode#267]
今天推送1.27.16版以后就无法上传函数了
点完deploy function就提示：
invalid signature: 0x6d783f3c

**Comment by PillarsZhang** [comment]
一样的错误，发生在 Local Run 和 Deploy（第一次使用

**Comment by caoyanbin1993** [comment]
我也是，第一次用

**Comment by sikros** [comment]
> 一样的错误，发生在 Local Run 和 Deploy（第一次使用

我降到1.27.15版了，之前版本都正常只有1.27.16有这个问题

**Comment by git-qfzhang** [comment]
现在已经解掉了哈
