### ISSUE TITLE
不支持服务属性 TracingConfig

### ISSUE THREAD

**Issue by iugo** [alibaba/serverless-vscode#274]
**Describe the bug**

在阿里云网页配置服务后, 导出配置, 其中有一项 “TracingConfig”, 但是会提示 “Unexpected property TracingConfig” 错误.

**To Reproduce**
1. 设置函数计算服务, 打开 “链路追踪”
2. 导出服务配置 yml, 能看到 TracingConfig 属性.
3. 在要上传的函数服务中配置 TracingConfig 属性, 标记为红色, 提示错误 “Unexpected property TracingConfig”.

**Expected behavior**

没有错误.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.2 (20D64)
 - VSCode Version: Version: 1.54.0-insider
 - Aliyun Serverless Extension Version v1.27.16

**Additional context**

**Comment by wells1013** [comment]
+1

**Comment by git-qfzhang** [comment]
最新版本已经修复
