### ISSUE TITLE
插件不兼容vscode 1.23.1版本 无法安装

### ISSUE THREAD

**Issue by goshawk-ym** [alibaba/serverless-vscode#3]
安装插件时提示
无法安装扩展“aliyun.aliyun-serverless-1.0.0”，它与 Code “1.23.1”不兼容。
VSCode 版本 1.23.1 (1.23.1)

**Comment by ChanDaoH** [comment]
Aliyun Serverless Extension v1.0.0 版本需要 VSCode IDE 版本不小于 1.31.0
之后插件的新版本会看是否需要降低这个限制。

**Comment by vangie** [comment]
vscode 1.23.1 是 18 年 4 月发布的，距现在已经一年多了，建议升级一下新版本。
