### ISSUE TITLE
更新系统到macos m1 monterey无法正常运行

### ISSUE THREAD

**Issue by youguo** [alibaba/serverless-vscode#315]
**Describe the bug**
无法正常运行。

**To Reproduce**
更新系统前可以正常使用，更新后出现如上问题。

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60578211/142749745-3647ccb9-fe61-4a92-bfe7-c11a2910a33c.png)

**Desktop (please complete the following information):**
 - OS: M1 MacOS Monterey  12.0.1
 - VSCode Version: 1.63.0-insider
 - Aliyun Serverless Extension Version: v1.27.18

**Comment by ruivolvos** [comment]
不只是M1会出现这个问题。我在旧的Intel处理器的Macbook Pro 上遇到了同样的报错。

**Comment by SquatsTonight** [comment]
Related to https://github.com/alibaba/serverless-vscode/issues/315
