### ISSUE TITLE
command 'fc.extension.bind.account' not found

### ISSUE THREAD

**Issue by ghost** [alibaba/serverless-vscode#316]
**Describe the bug**
点击绑定账号，显示错误 `command 'fc.extension.bind.account' not found`

**Expected behavior**
可以绑定账号

**Screenshots**
![image](https://user-images.githubusercontent.com/20895125/143172213-bbc568aa-7600-4ed1-bba7-357e00d5be80.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1 (Intel)
 - VSCode Version: 
   ```
     版本: 1.62.3
    日期: 2021-11-17T07:59:13.865Z (6 天前)
    Electron: 13.5.2
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Darwin x64 21.1.0
   ```
 - Aliyun Serverless Extension Version: v1.27.18

**Comment by ruivolvos** [comment]
我遇到了同样的问题 @ChanDaoH 请问如何解决

**Comment by SquatsTonight** [comment]
Fix in Release 1.27.19

**Comment by archeraya** [comment]
新版本也出现了同样的问题，1.27.19

- OS：Mac 13.0.1

- VSCode Version：1.73.1
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0

- Aliyun Serverless Extension Version: v1.27.19

**Comment by fudg1211** [comment]
还有这个问题
