### ISSUE TITLE
页面显示‘当前没有可提供视图数据的提供来源进行注册’

### ISSUE THREAD

**Issue by kxxxxx** [alibaba/serverless-vscode#33]
点击注册会显示command 'fc.extension.bind.account' not found

**Comment by ChanDaoH** [comment]
所在的操作系统环境是什么？

**Comment by kxxxxx** [comment]
linux   manjaro


 
---原始邮件---
发件人: "William"<notifications@github.com>
发送时间: 2019年7月31日 18:05:35
收件人: "alibaba/serverless-vscode"<serverless-vscode@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"kxxxxx"<940064306@qq.com>;
主题: Re: [alibaba/serverless-vscode] 页面显示‘当前没有可提供视图数据的提供来源进行注册’ (#33)



所在的操作系统环境是什么？

**Comment by kxxxxx** [comment]
> 所在的操作系统环境是什么？
您好，有查到问题吗？

**Comment by ChanDaoH** [comment]
现有版本未发现相关问题，有新情况麻烦新开 issue 同步哈
