### ISSUE TITLE
在 Local resource 区域单击函数，template.yml 中光标指向了错误的位置

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#45]
**Describe the bug**
点击函数，光标指向了 template.yml 中错误的位置

**To Reproduce**
1. 在一个服务下创建多个函数
2. 点击除第一个函数之外任意的函数
3. 右侧的 template.yml 显示区域中，光标指向了错误的位置

**Expected behavior**
光标指向该函数所在的位置

**Screenshots**
![image](https://user-images.githubusercontent.com/626967/62406569-9fcfac80-b5e0-11e9-98fb-c719f4675463.png)

**Desktop (please complete the following information):**
 - OS: [MacOS 10.14.6]
 - VSCode Version: [e.g. 1.36.1]
 - Aliyun Serverless Extension Version [e.g. 1.3.0]

**Additional context**

**Comment by ChanDaoH** [comment]
![bug反馈](https://user-images.githubusercontent.com/19430792/62407464-8122e300-b5eb-11e9-990e-ac66c013f287.gif)

本地没有复现出来，是否可以提供下相关的 GIF 图或操作步骤呢？
