### ISSUE TITLE
Local resource 资源管理增强

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#46]
**Is your feature request related to a problem? Please describe.**
1. 在 local resource 中，能否双击函数显示代码？而不是显示 template.yml 中的内容。
2. 在 local resource 中，单击服务/函数时，除了光标指向 template.yml 中对应的位置外，能否该服务/函数整个区域都闪烁一下，提醒用户这些属性都属于这个服务/函数？

**Comment by vangie** [comment]
块标注可以参考这个 https://github.com/microsoft/monaco-editor/issues/1529

**Comment by vangie** [comment]
@hryang 目前 VSCode 提供树还没有支持绑定 Double Click 的能力，https://github.com/Microsoft/vscode/issues/27823
