### ISSUE TITLE
删除服务/函数

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#48]
**Is your feature request related to a problem? Please describe.**
在 fun 中如何服务/函数资源？当前在 template.yml 中删除相关的资源，左侧的 local resource 面板还会显示。

![image](https://user-images.githubusercontent.com/626967/62478678-387f4b80-b7de-11e9-8e08-bf9632bc613f.png)

**Comment by ChanDaoH** [comment]
已发布，在编辑 template 并保存后，会自动刷新左侧的本地资源树
