### ISSUE TITLE
支持调用使用 http trigger 的函数

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#49]
**Is your feature request related to a problem? Please describe.**
当前 fun 只支持 event function 的调用，希望也能支持远程调用包含 http trigger 的函数。方便用户调试。

**Describe the solution you'd like**
短期内 fun 能够显示 http function 的 url，方便在浏览器中贴上地址直接测试。系统性解决，可以考虑集成 postman 等调试工具。

**Describe alternatives you've considered**

**Additional context**

**Comment by ChanDaoH** [comment]
已发布，调用远端 HTTP Trigger 函数后，提供访问链接
