### ISSUE TITLE
更便捷的显示函数代码

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#5]
如图所示，希望在左侧边栏单击函数的时候显示函数代码

![image](https://user-images.githubusercontent.com/626967/61014577-c2442080-a3ba-11e9-90a0-0ef04e77f47c.png)

**Comment by vangie** [comment]
如果一个 service 下面有很多函数，点击 service 进入 template.yml 编辑函数的区块还是不够方便，而且点击不同的部分进入不同的文件也不符合自觉。

这块我觉得
* 点击保持一致，双击函数进入代码。
* 另外在 template.yml 的 Handler 里做一个补充，按住 ctrl 或者 command 键鼠标点击 index.handler 可以进入对应函数（这个也常见 IDE 的使用方式）
