### ISSUE TITLE
如何允许用户配置/自定义本地运行/调试功能

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#8]
比如用户在本地单步调试通过后，然后开始针对函数跑一组测试。此时用户希望函数的 sandbox 是常驻的，这样能迅速跑完测试用例。如果每次调用都起一个 sandbox，速度太慢。

![image](https://user-images.githubusercontent.com/626967/61015655-118c5000-a3bf-11e9-9f08-556f912343cb.png)

**Comment by vangie** [comment]
@hryang 这里说跑一组测试的具体是怎么使用的。指触发某个脚本，还是反复点运行，抑或是反复点调试。我理解跑测试用例需要构造很多不同的输入条件，那需要写脚本的。我们这里还缺失了针对函数的测试框架不仅是工具层面的东西。

另外，运行和调试启动的 container 是不同的参数。这里的核心诉求是什么，多次调试之间启动有点慢么？

**Comment by vangie** [comment]
@hryang 允许用户配置本地调试功能的意图是什么呢？具体怎么配置，这个时刻点不太理解，能展开一下么？

**Comment by ChanDaoH** [comment]
现有版本已提供了 Invoke Panel
支持修改 event 信息，常驻型或一次性容器
