### ISSUE TITLE
管理多账户多区域的云端资源

### ISSUE THREAD

**Issue by hryang** [alibaba/serverless-vscode#9]
Remote resource 的管理支持多账户多区域

**Comment by ChanDaoH** [comment]
![image](https://user-images.githubusercontent.com/19430792/61016586-b9574d00-a3c2-11e9-9d10-e7d89b760b23.png)
目前插件支持单账号下快速切换区域，如果要更换账号需要重新 Bind New Account，下个版本会考虑记录下 Account，支持直接切换

**Comment by hryang** [comment]
vscode 应该不需要做什么，fun 要支持多账户的管理。
